apiVersion: apps/v1
kind: Deployment
metadata:
  name: centralhub
  namespace: kafka-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centralhub
  template:
    metadata:
      labels:
        app: centralhub
    spec:
      containers:
      - name: centralhub
        image: centralhub:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: Kafka__BootstrapServers
          value: "kafka:9092"
        - name: ServiceUrls__OrderService
          value: "http://orderservice:8080"
        - name: ServiceUrls__PartnerService
          value: "http://partnerservice:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: centralhub
  namespace: kafka-demo
spec:
  type: NodePort
  selector:
    app: centralhub
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
