apiVersion: apps/v1
kind: Deployment
metadata:
  name: partnerservice
  namespace: kafka-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: partnerservice
  template:
    metadata:
      labels:
        app: partnerservice
    spec:
      containers:
      - name: partnerservice
        image: partnerservice:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: Kafka__BootstrapServers
          value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: partnerservice
  namespace: kafka-demo
spec:
  type: NodePort
  selector:
    app: partnerservice
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30002
