apiVersion: v1
kind: ConfigMap
metadata:
  name: mtogo-config
  namespace: mtogo
  labels:
    app.kubernetes.io/part-of: mtogo-platform
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"
  Kafka__BootstrapServers: "kafka:29092"
